apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-clickbait-gloo"
  namespace: kubeflow
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: julionevadod/clickbait-detector-kubeflow:dev
              command: 
                - torchrun 
                - training/train.py
              volumeMounts:
              - name: create-pvc
                mountPath: /mnt
          volumes:
            - name: create-pvc
              persistentVolumeClaim:
                claimName: clickbait-detection-training-pipeline-cvtvx-training-pipeline-pvc
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers: 
            - name: pytorch
              image: julionevadod/clickbait-detector-kubeflow:dev
              command: 
              - torchrun 
              - training/train.py
              volumeMounts:
              - name: create-pvc
                mountPath: /mnt
          volumes:
            - name: create-pvc
              persistentVolumeClaim:
                claimName: clickbait-detection-training-pipeline-cvtvx-training-pipeline-pvc
